server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tz?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.tz_demo.entity
logging:
  level:
    .com.example.tz_demo: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

device_default_amount: 1000

# token的过期时间
jwt:
  expire: 3600